### ISSUE TITLE
Pages re-load for <a /> tags in React

### ISSUE THREAD

**Issue by krzemLech** [piercefreeman/mountaineer#136]
When using React Router, it gives as a <Link /> component that allows to navigate to a different url without a page reload. 
In Mountaineer I cannot see a similar functionality. 

The documentation suggests using simple anchor tag which refersh page and the app state is lost every time. The questions are following:

1. Is this an intended behaviour? 
2. If yes, then how can we navigate without loosing the application global state?
3. If no, then how can we emulate this non-refresh behaviour?

**Comment by piercefreeman** [comment]
Hi @krzemLech -

React Router relies on your whole site being a single-page app in order to provide the functionality you're describing. When you click on a router link, it will change the window.location.href of the browser window but it won't actually invoke a new server side request for the new page. This is beneficial in some cases - but it makes your site overly reliant on client side javascript to load your entire app into memory on the initial page load.

Instead, Mountaineer focuses more on the server side logic where we say that one client request yields one page. Switching to a new page via an href will start the client->server->client loop again. This is often better for SEO and accessibility, and provides a lot of the simplification conventions that are baked into the library.

If you really want behavior similar to react-router with Mountaineer, I recommend something like [turbolinks](https://github.com/turbolinks/turbolinks) that in the background fetches the new html page from the new url and hot-swaps the local window's html.

**Comment by piercefreeman** [comment]
@krzemLech Closing this out for now, let me know if you have any additional questions on behavior here.
