### ISSUE TITLE
Support for Python 3.10

### ISSUE THREAD

**Issue by oguzhanmeteozturk** [piercefreeman/mountaineer#98]
I’m really excited about the potential of mountaineer and looking forward to use it in some projects. However most of my experiments are tied to Python 3.10 because of other dependencies, and upgrading to Python 3.11 isn't feasible just yet.

Would you consider adding support for Python 3.10? I understand this might add some maintenance overhead, but I've already taken a stab at it. There are a few hiccups with type subscripts and the absence of string enums is a little annoying. Yet most tests are passing.

**Comment by piercefreeman** [comment]
@oguzhanmeteozturk This ended up being easier than expected. I've merged in initial support in https://github.com/piercefreeman/mountaineer/pull/105. 3.9 would be a tougher lift, mostly on the type-hinting side since it lacks language-level support for union-like primitives (ie. `str | None`).

Let me know if you see any issues in [v0.5.0.dev2](https://github.com/piercefreeman/mountaineer/releases/tag/v0.5.0.dev2). Going to close out this thread for now.
